; PlatformIO - UART Polling Echo
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; Pastikan port ini sesuai dengan yang muncul di Device Manager setelah install driver
upload_port = COM6